### ISSUE TITLE
Checklist for open sourcing

### ISSUE THREAD

**Issue by laraross** [amperser/proselint#198]
- [x] Hook up travis-ci.org  
~~- [ ] Test installation in an empty virtual environment, and maybe even a fresh OS install~~ see below
- [x] Submit to pypi
- [x] Protect master branch

**Comment by michaelpacer** [comment]
-[ ] test installation on fresh virtualenv python2
-[ ] test installation on fresh virtualenv python3
-[ ] test installation on fresh OS install python2
-[ ] test installation on fresh OS install python3
